package.json, src/multi-select/dropdown.tsx, src/multi-select/index.tsx, src/multi-select/loading.tsx, src/select-panel/default-item.tsx, src/select-panel/index.tsx, src/select-panel/select-item.tsx, src/select-panel/select-list.tsx, yarn.lock
This one address #3.
I added the amazing `@ampproject/filesize` to track the filesize across builds. It doesn't run now as in is not hooked into `build` or other, so one would have to run it with `yarn filesize`. It can be part of the build step, I didn't want to add too many things at once. 😃 
Let me know your thoughts.
=> (feat) Switch to object styles to shave size and gain perf

package.json, src/select-panel/index.tsx, yarn.lock
Closes #46 
Hides "select all" on querying as it can be misleading if user performs select all while filtering
=> hide selectAll on filtering

package.json, src/select-panel/default-item.tsx
=> removed global style leak

src/multi-select/dropdown.tsx
Addressing question raised in https://github.com/harshzalavadiya/react-multi-select-component/issues/67
=> Do not expand if disabled.

package.json, src/select-panel/index.tsx
=> select all checked on open

package.json, src/select-panel/index.tsx, yarn.lock
=> :bug: space not allowed in search input

src/select-panel/index.tsx
Fix for Issue #143 
Select all will be shown if the search filter is applied and if there are valid options.
If there is no option or if all options are disabled select all will not be shown.
=> Show Select All With Filter Applied

README.md, src/lib/get-string.tsx, src/lib/interfaces.ts, src/multi-select/dropdown.tsx, src/multi-select/index.tsx
Added button to clear selected Items. That will show up only when a value is selected.
Added a new prop to allow the user to change the default clear icon.
=> Add clear selected items button

src/select-panel/index.tsx
=> :bug: unable to select last item

README.md, package.json, src/lib/interfaces.ts, src/multi-select/dropdown.tsx, src/multi-select/index.tsx
=> :sparkles: added `isOpen` and `defaultIsOpen` prop

.github/workflows/main.yml, .github/workflows/release.yml
=> ci: :construction_worker: cleaned up CI title

package.json, src/multi-select/dropdown.tsx, yarn.lock
=> fix: :bug: added disabled prop to clear button

README.md, package.json, src/hooks/use-multi-select.tsx, src/lib/interfaces.ts, src/select-panel/index.tsx, stories/custom-filter.stories.tsx
=> refactor: :recycle: async filterOptions support

src/hooks/use-did-update-effect.tsx, src/multi-select/dropdown.tsx, stories/custom-arrow.stories.tsx
=> fix: :bug: onMenuToggle skip callback on initial render

.storybook/main.js, README.md, package.json, src/hooks/use-key.tsx, src/hooks/use-multi-select.tsx, src/lib/classnames.ts, src/lib/constants.tsx, src/lib/interfaces.ts, src/multi-select/dropdown.tsx, src/multi-select/index.tsx, src/multi-select/loading.tsx, src/select-panel/default-item.tsx, src/select-panel/index.tsx, src/select-panel/select-item.tsx, src/select-panel/select-list.tsx, src/style.css, stories/basic.stories.tsx, stories/custom-element-story.css, stories/custom-element.stories.tsx, tsdx.config.js, yarn.lock
Resolves #201
Resolves #307
Resolves #197
=> refactor: :recycle: ref based navigation

.husky/pre-commit, README.md, package.json, src/multi-select/dropdown.tsx, yarn.lock
=> fix: :bug: search input space not allowed

src/hooks/use-multi-select.tsx
=> fix: :bug: props.options not updating from outside

package.json, src/style.css, yarn.lock
=> Usablity border color

package.json, src/hooks/use-multi-select.tsx
fixes flicker glitch while production bundle does initial render in create react app
=> reactor: :recycle: flicker fix on init

.storybook/main.js, package.json, src/select-panel/index.tsx, yarn.lock
Closes https://github.com/hc-oss/react-multi-select-component/pull/515
=> fix: :bug: custom filter selection

src/lib/simple-match-utils.tsx, src/select-panel/index.tsx
Resolves #542
In non english languages fuzzy search was not working as expected, so by default algorithm defaults to substring search
=> refactor: :recycle: updated filter logic

src/select-panel/index.tsx
Continuation of https://github.com/hc-oss/react-multi-select-component/pull/606 since it requires some cleanup + rebase of all commits
=> refactor: :recycle: cont. allow create option when there are matches

src/select-panel/default-item.tsx, src/select-panel/select-item.tsx
=> refactor: :recycle: no undefined in className
